# This is a config for E2B sandbox template.
# You can use template ID (tzmo9yev72awyg0nctw9) or template name (nextjs-shadcn-kunal) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("nextjs-shadcn-kunal") # Sync sandbox
# sandbox = await AsyncSandbox.create("nextjs-shadcn-kunal") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nextjs-shadcn-kunal')

team_id = "b7c61442-dc9c-402c-bba1-5edd3756ea6a"
dockerfile = "e2b.Dockerfile"
template_name = "nextjs-shadcn-kunal"
template_id = "tzmo9yev72awyg0nctw9"
